/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechRouteImport } from './routes/tech'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TechTimeRouteImport } from './routes/tech.time'
import { Route as TechPayrollRouteImport } from './routes/tech.payroll'
import { Route as TechCalculatorRouteImport } from './routes/tech.calculator'
import { Route as TechAvailableRouteImport } from './routes/tech.available'
import { Route as AdminTechniciansRouteImport } from './routes/admin.technicians'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as TechJobsIndexRouteImport } from './routes/tech.jobs.index'
import { Route as TechJobsJobIdRouteImport } from './routes/tech.jobs.$jobId'

const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TechTimeRoute = TechTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => TechRoute,
} as any)
const TechPayrollRoute = TechPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => TechRoute,
} as any)
const TechCalculatorRoute = TechCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => TechRoute,
} as any)
const TechAvailableRoute = TechAvailableRouteImport.update({
  id: '/available',
  path: '/available',
  getParentRoute: () => TechRoute,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const TechJobsIndexRoute = TechJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => TechRoute,
} as any)
const TechJobsJobIdRoute = TechJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => TechRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/tech': typeof TechRouteWithChildren
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/tech/available': typeof TechAvailableRoute
  '/tech/calculator': typeof TechCalculatorRoute
  '/tech/payroll': typeof TechPayrollRoute
  '/tech/time': typeof TechTimeRoute
  '/admin/': typeof AdminIndexRoute
  '/tech/': typeof TechIndexRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/tech/available': typeof TechAvailableRoute
  '/tech/calculator': typeof TechCalculatorRoute
  '/tech/payroll': typeof TechPayrollRoute
  '/tech/time': typeof TechTimeRoute
  '/admin': typeof AdminIndexRoute
  '/tech': typeof TechIndexRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/tech/jobs': typeof TechJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/tech': typeof TechRouteWithChildren
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/tech/available': typeof TechAvailableRoute
  '/tech/calculator': typeof TechCalculatorRoute
  '/tech/payroll': typeof TechPayrollRoute
  '/tech/time': typeof TechTimeRoute
  '/admin/': typeof AdminIndexRoute
  '/tech/': typeof TechIndexRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/tech'
    | '/admin/payroll'
    | '/admin/schedule'
    | '/admin/technicians'
    | '/tech/available'
    | '/tech/calculator'
    | '/tech/payroll'
    | '/tech/time'
    | '/admin/'
    | '/tech/'
    | '/tech/jobs/$jobId'
    | '/tech/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/payroll'
    | '/admin/schedule'
    | '/admin/technicians'
    | '/tech/available'
    | '/tech/calculator'
    | '/tech/payroll'
    | '/tech/time'
    | '/admin'
    | '/tech'
    | '/tech/jobs/$jobId'
    | '/tech/jobs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/tech'
    | '/admin/payroll'
    | '/admin/schedule'
    | '/admin/technicians'
    | '/tech/available'
    | '/tech/calculator'
    | '/tech/payroll'
    | '/tech/time'
    | '/admin/'
    | '/tech/'
    | '/tech/jobs/$jobId'
    | '/tech/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  TechRoute: typeof TechRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tech/time': {
      id: '/tech/time'
      path: '/time'
      fullPath: '/tech/time'
      preLoaderRoute: typeof TechTimeRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/payroll': {
      id: '/tech/payroll'
      path: '/payroll'
      fullPath: '/tech/payroll'
      preLoaderRoute: typeof TechPayrollRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/calculator': {
      id: '/tech/calculator'
      path: '/calculator'
      fullPath: '/tech/calculator'
      preLoaderRoute: typeof TechCalculatorRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/available': {
      id: '/tech/available'
      path: '/available'
      fullPath: '/tech/available'
      preLoaderRoute: typeof TechAvailableRouteImport
      parentRoute: typeof TechRoute
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tech/jobs/': {
      id: '/tech/jobs/'
      path: '/jobs'
      fullPath: '/tech/jobs/'
      preLoaderRoute: typeof TechJobsIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/jobs/$jobId': {
      id: '/tech/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/tech/jobs/$jobId'
      preLoaderRoute: typeof TechJobsJobIdRouteImport
      parentRoute: typeof TechRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminTechniciansRoute: typeof AdminTechniciansRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPayrollRoute: AdminPayrollRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminTechniciansRoute: AdminTechniciansRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TechRouteChildren {
  TechAvailableRoute: typeof TechAvailableRoute
  TechCalculatorRoute: typeof TechCalculatorRoute
  TechPayrollRoute: typeof TechPayrollRoute
  TechTimeRoute: typeof TechTimeRoute
  TechIndexRoute: typeof TechIndexRoute
  TechJobsJobIdRoute: typeof TechJobsJobIdRoute
  TechJobsIndexRoute: typeof TechJobsIndexRoute
}

const TechRouteChildren: TechRouteChildren = {
  TechAvailableRoute: TechAvailableRoute,
  TechCalculatorRoute: TechCalculatorRoute,
  TechPayrollRoute: TechPayrollRoute,
  TechTimeRoute: TechTimeRoute,
  TechIndexRoute: TechIndexRoute,
  TechJobsJobIdRoute: TechJobsJobIdRoute,
  TechJobsIndexRoute: TechJobsIndexRoute,
}

const TechRouteWithChildren = TechRoute._addFileChildren(TechRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  TechRoute: TechRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
