/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechRouteImport } from './routes/tech'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechIndexRouteImport } from './routes/tech.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as TechTimeRouteImport } from './routes/tech.time'
import { Route as TechPayrollRouteImport } from './routes/tech.payroll'
import { Route as TechCalculatorRouteImport } from './routes/tech.calculator'
import { Route as TechAvailableRouteImport } from './routes/tech.available'
import { Route as OwnerTeamRouteImport } from './routes/owner.team'
import { Route as OwnerPayrollRouteImport } from './routes/owner.payroll'
import { Route as OwnerIntakeRouteImport } from './routes/owner.intake'
import { Route as TechJobsIndexRouteImport } from './routes/tech.jobs.index'
import { Route as TechJobsJobIdRouteImport } from './routes/tech.jobs.$jobId'

const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const TechTimeRoute = TechTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => TechRoute,
} as any)
const TechPayrollRoute = TechPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => TechRoute,
} as any)
const TechCalculatorRoute = TechCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => TechRoute,
} as any)
const TechAvailableRoute = TechAvailableRouteImport.update({
  id: '/available',
  path: '/available',
  getParentRoute: () => TechRoute,
} as any)
const OwnerTeamRoute = OwnerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPayrollRoute = OwnerPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerIntakeRoute = OwnerIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => OwnerRoute,
} as any)
const TechJobsIndexRoute = TechJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => TechRoute,
} as any)
const TechJobsJobIdRoute = TechJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => TechRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/tech': typeof TechRouteWithChildren
  '/owner/intake': typeof OwnerIntakeRoute
  '/owner/payroll': typeof OwnerPayrollRoute
  '/owner/team': typeof OwnerTeamRoute
  '/tech/available': typeof TechAvailableRoute
  '/tech/calculator': typeof TechCalculatorRoute
  '/tech/payroll': typeof TechPayrollRoute
  '/tech/time': typeof TechTimeRoute
  '/owner/': typeof OwnerIndexRoute
  '/tech/': typeof TechIndexRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner/intake': typeof OwnerIntakeRoute
  '/owner/payroll': typeof OwnerPayrollRoute
  '/owner/team': typeof OwnerTeamRoute
  '/tech/available': typeof TechAvailableRoute
  '/tech/calculator': typeof TechCalculatorRoute
  '/tech/payroll': typeof TechPayrollRoute
  '/tech/time': typeof TechTimeRoute
  '/owner': typeof OwnerIndexRoute
  '/tech': typeof TechIndexRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/tech/jobs': typeof TechJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner': typeof OwnerRouteWithChildren
  '/tech': typeof TechRouteWithChildren
  '/owner/intake': typeof OwnerIntakeRoute
  '/owner/payroll': typeof OwnerPayrollRoute
  '/owner/team': typeof OwnerTeamRoute
  '/tech/available': typeof TechAvailableRoute
  '/tech/calculator': typeof TechCalculatorRoute
  '/tech/payroll': typeof TechPayrollRoute
  '/tech/time': typeof TechTimeRoute
  '/owner/': typeof OwnerIndexRoute
  '/tech/': typeof TechIndexRoute
  '/tech/jobs/$jobId': typeof TechJobsJobIdRoute
  '/tech/jobs/': typeof TechJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/tech'
    | '/owner/intake'
    | '/owner/payroll'
    | '/owner/team'
    | '/tech/available'
    | '/tech/calculator'
    | '/tech/payroll'
    | '/tech/time'
    | '/owner/'
    | '/tech/'
    | '/tech/jobs/$jobId'
    | '/tech/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner/intake'
    | '/owner/payroll'
    | '/owner/team'
    | '/tech/available'
    | '/tech/calculator'
    | '/tech/payroll'
    | '/tech/time'
    | '/owner'
    | '/tech'
    | '/tech/jobs/$jobId'
    | '/tech/jobs'
  id:
    | '__root__'
    | '/'
    | '/owner'
    | '/tech'
    | '/owner/intake'
    | '/owner/payroll'
    | '/owner/team'
    | '/tech/available'
    | '/tech/calculator'
    | '/tech/payroll'
    | '/tech/time'
    | '/owner/'
    | '/tech/'
    | '/tech/jobs/$jobId'
    | '/tech/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  TechRoute: typeof TechRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/tech/time': {
      id: '/tech/time'
      path: '/time'
      fullPath: '/tech/time'
      preLoaderRoute: typeof TechTimeRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/payroll': {
      id: '/tech/payroll'
      path: '/payroll'
      fullPath: '/tech/payroll'
      preLoaderRoute: typeof TechPayrollRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/calculator': {
      id: '/tech/calculator'
      path: '/calculator'
      fullPath: '/tech/calculator'
      preLoaderRoute: typeof TechCalculatorRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/available': {
      id: '/tech/available'
      path: '/available'
      fullPath: '/tech/available'
      preLoaderRoute: typeof TechAvailableRouteImport
      parentRoute: typeof TechRoute
    }
    '/owner/team': {
      id: '/owner/team'
      path: '/team'
      fullPath: '/owner/team'
      preLoaderRoute: typeof OwnerTeamRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/payroll': {
      id: '/owner/payroll'
      path: '/payroll'
      fullPath: '/owner/payroll'
      preLoaderRoute: typeof OwnerPayrollRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/intake': {
      id: '/owner/intake'
      path: '/intake'
      fullPath: '/owner/intake'
      preLoaderRoute: typeof OwnerIntakeRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/tech/jobs/': {
      id: '/tech/jobs/'
      path: '/jobs'
      fullPath: '/tech/jobs/'
      preLoaderRoute: typeof TechJobsIndexRouteImport
      parentRoute: typeof TechRoute
    }
    '/tech/jobs/$jobId': {
      id: '/tech/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/tech/jobs/$jobId'
      preLoaderRoute: typeof TechJobsJobIdRouteImport
      parentRoute: typeof TechRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerIntakeRoute: typeof OwnerIntakeRoute
  OwnerPayrollRoute: typeof OwnerPayrollRoute
  OwnerTeamRoute: typeof OwnerTeamRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerIntakeRoute: OwnerIntakeRoute,
  OwnerPayrollRoute: OwnerPayrollRoute,
  OwnerTeamRoute: OwnerTeamRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface TechRouteChildren {
  TechAvailableRoute: typeof TechAvailableRoute
  TechCalculatorRoute: typeof TechCalculatorRoute
  TechPayrollRoute: typeof TechPayrollRoute
  TechTimeRoute: typeof TechTimeRoute
  TechIndexRoute: typeof TechIndexRoute
  TechJobsJobIdRoute: typeof TechJobsJobIdRoute
  TechJobsIndexRoute: typeof TechJobsIndexRoute
}

const TechRouteChildren: TechRouteChildren = {
  TechAvailableRoute: TechAvailableRoute,
  TechCalculatorRoute: TechCalculatorRoute,
  TechPayrollRoute: TechPayrollRoute,
  TechTimeRoute: TechTimeRoute,
  TechIndexRoute: TechIndexRoute,
  TechJobsJobIdRoute: TechJobsJobIdRoute,
  TechJobsIndexRoute: TechJobsIndexRoute,
}

const TechRouteWithChildren = TechRoute._addFileChildren(TechRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  TechRoute: TechRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
